<?php

namespace Database\Seeders;

use App\Models\Tag;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tags = collect([
            'Laravel',
            'PHP',
            'JavaScript',
            'Vue.js',
            'React.js',
            'Angular',
            'Node.js',
            'Express.js',
            'MongoDB',
            'MySQL',
            'PostgreSQL',
            'SQLite',
            'Redis',
            'Docker',
            'Kubernetes',
            'AWS',
            'Azure',
            'Google Cloud',
            'CI/CD',
            'Testing',
            'TDD',
            'BDD',
            'DDD',
            'SOLID',
            'Design Patterns',
            'Refactoring',
            'Clean Code',
            'Clean Architecture',
            'Microservices',
            'REST',
            'GraphQL',
            'API',
            'Websockets',
            'Webhooks',
            'OAuth',
            'JWT',
            'SAML',
            'OpenID Connect',
            'OAuth2',
            'Data Structures',
            'SAML2',
            'HTML',
            'CSS',
            'SASS',
            'Tailwind CSS',
            'Bootstrap',
            'TypeScript',
            'jQuery',
            'Web Development',
            'Mobile Development',
            'Android',
            'iOS',
            'Flutter',
            'Swift',
            'Kotlin',
            'Xamarin',
            'Unity',
            'Game Development',
            'Artificial Intelligence',
            'Machine Learning',
            'Deep Learning',
            'Computer Vision',
            'Natural Language Processing',
            'Big Data',
            'Hadoop',
            'Spark',
            'Kafka',
            'Cybersecurity',
            'Penetration Testing',
            'Firewall',
            'Encryption',
            'DevOps',
            'Ansible',
            'Terraform',
            'Serverless',
            'Blockchain',
            'Bitcoin',
            'Ethereum',
            'Cryptography',
            'Quantum Computing',
            'IoT',
            'Raspberry Pi',
            'Arduino',
            'Networking',
            'VPN',
            'Cloud Computing',
            'Virtualization',
            'VMware',
            'Hyper-V',
            'PowerShell',
            'Linux',
            'Ubuntu',
            'CentOS',
            'Debian',
            'Bash',
            'Shell Scripting',
            'Performance Optimization',
            'Scalability',
            'Load Balancing',
            'Caching',
            'CDN',
            'Logging',
            'Monitoring',
            'Elastic Stack',
            'Prometheus',
            'Grafana',
            'Jenkins',
            'Git',
            'GitHub',
            'GitLab',
            'Bitbucket',
            'Agile',
            'Scrum',
            'Kanban',
            'Project Management',
            'Figma',
            'UI/UX Design',
            'Prototyping',
            'Accessibility',
            'SEO',
            'Analytics',
            'Marketing Automation',
        ]);

        $tags->each(fn ($tag) => Tag::create([
            'name' => $tag,
            'slug' => Str::slug($tag),
        ]));
    }
}
